
# targetDirectory where you plan lineman to run.
# targetDirectory consume 'rel', 'abs' and '~'' paths
targetDirectory = "/path/to/directory/for/lineman/traversing/"

# [[configElement]] sections are unlimited
[[configElement]]
# Target directory has files
hasFiles         = []

# Target directory has directories
hasDirectories   = ["dist-newstyle"]

# Target directory has extensions.
# It consume exts with and without '.'
hasExtensions    = []

# Command to run in searched directories
command          = "cabal"

# Command's arguments
args             = ["clean"]

