
# targetDirectory consume 'rel', 'abs' and '~'' paths
targetDirectory = "/path/to/your/directory/where/you/run/lineman/"

[[configElement]]
# Target directory has files
hasFiles         = ["readme.txt"]

# Target directory has directories
hasDirectories   = []

# Target directory has extensions.
# It consume exts with and without '.'
hasExtensions    = []

# Command to run in searched directories
command          = "rm"

# Command's arguments
args             = ["readme.txt"]

[[configElement]]
# Target directory has files
hasFiles         = []

# Target directory has directories
hasDirectories   = []

# Target directory has extensions.
# It consume exts with and without '.'
hasExtensions    = []

# Command to run in searched directories
command          = "touch"

# Command's arguments
args             = ["readme.txt"]
