
# taregetDirectory consume 'rel', 'abs' and '~'' paths
taregetDirectory = "/home/metaxis/sources/Haskell/education/haskell-in-depth/"

[[configElement]]
# Target directory has files
hasFiles         = []

# Target directory has directories
hasDirectories   = ["dist-newstyle"]

# Target directory has extensions.
# It consume exts with and without '.'
hasExtensions    = []

# Command to run in searched directories
command          = "rm"

# Command's arguments
args             = ["-rf","dist-newstyle"]

[[configElement]]
# Target directory has files
hasFiles         = []

# Target directory has directories
hasDirectories   = [".stack-work"]

# Target directory has extensions.
# It consume exts with and without '.'
hasExtensions    = []

# Command to run in searched directories
command          = "rm"

# Command's arguments
args             = ["-rf",".stack-work"]
